- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload
    
- platform: google_travel_time
  name: Phone To Home
  api_key: !secret googleapi
  origin: device_tracker.iphone
  destination: zone.home
  
- platform: template
  sensors:
    battery_iphone:
      friendly_name: iPhone
      unit_of_measurement: '%'
      value_template: >
          {%- if states.device_tracker.iphone.attributes.battery %}
              {{ states.device_tracker.iphone.attributes.battery|round }}
          {% else %}
              {{ states.sensor.battery_iphone.state }}
          {%- endif %}
      icon_template: '{%- if is_state("sensor.battery_iphone", "unknown") %}mdi:battery-unknown{%- elif is_state_attr("device_tracker.user_ios01", "battery_status", "Charging") %}mdi:battery-charging{%- elif  states.device_tracker.user_ios01.attributes.battery <= 5 %}mdi:battery-outline{%- elif states.device_tracker.user_ios01.attributes.battery >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.device_tracker.user_ios01.attributes.battery|float / 10)|round*10}}{%- endif %}'

- platform: pi_hole
      
- platform: synologydsm
  host: 192.168.1.3
  username: Superlangbein
  password: !secret synology-password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up  
    - network_down      
    - disk_status
    - volume_status      
    
- platform: netatmo
  station: Kjellerstue
  modules:
    Kjellersoverom:
      - temperature
      - humidity
      - min_temp
      - max_temp
      - battery_vp
    Kjellerstue:
      - temperature
      - co2
      - pressure
      - noise
      - humidity
    
- platform: netatmo
  station: Søbakkvegen
  modules:
    Ute:
      - temperature
      - humidity
      - min_temp
      - max_temp
      - battery_vp
    Stue:
      - temperature
      - co2
      - pressure
      - noise
      - humidity