
alias: 'Aktiver garasjeport'
initial_state: 'on'
trigger:
  platform: time
  after: '07:00:00'
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: script.turn_on
    entity_id: script.garage
