alias: 'Alert when dryer is done'
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.torketrommel
  from: "on"
  to: "off"
action:
  - service: notify.pushbullet
    data:
      title: 'Jarvis'
      message: 'Tørketrommel er ferdig.'
	  
