alias: Slå av alle stuelys
initial_state: 'on'
trigger:
  platform: state
  entity_id: input_boolean.allestuelys
action:
  - service_template: 'switch.turn_{{trigger.to_state.state}}'
    data:
      entity_id: switch.rf04,switch.rf02,switch.rf03,switch.rf05
  - service_template: 'light.turn_{{trigger.to_state.state}}'
    data:
      entity_id: light.h01
