alias: 'Batteri Alarm for iPad'
initial_state: 'on'
trigger:
  - platform: numeric_state
    entity_id: sensor.superlangbeins_ipro_battery_level
    below: 20
action:
  - service: notify.alle
    data:
      title: 'HelleBOT'
      message: 'iPad Pro batteriet er lavt, koble til lader'
