alias: Automation for when 'HelleBOT' starts
initial_state: 'on'
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.pushbullet
    data:
      title: 'HelleBOT'
      message: 'Klar til tjeneste'
  - service: mqtt.publish
    data:
      topic: HA/cover
      payload: '-'
