alias: Automation for when 'Jarvis' starts
initial_state: 'on'
trigger:
  - platform: homeassistant
    event: start
action:
  - service: notify.pushbullet
    data:
      title: 'Jarvis'
      message: 'Jarvis started successfully.'
  - service: mqtt.publish
    data:
      topic: HA/cover
      payload: '-'
