alias: Slå av kaffetrakter etter to timer
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.rf06
    to: 'on'
action:
  - delay:
      minutes: 120
  - service: input_boolean.turn_off
    entity_id: input_boolean.rf06
