alias: 'Morgen lys'
initial_state: 'on'
trigger:
  platform: time
  after: '21:15:00'
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: switch.rf04
    state: 'off'
action:
  - service: light.turn_off
