alias: Slå på alle stuelys
initial_state: 'on'
trigger:
  platform: state
  entity_id: switch.stua
  from: "off"
  to: "on"
action:
  - service: light.turn_on
    data:
      entity_id: light.h01
      brightness: 255
