alias: 'Morgen lys'
initial_state: 'on'
trigger:
  platform: time
  after: '06:30:00'
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.rf04
