alias: Notify when garageport is activated
initial_state: 'on'
trigger:
  - platform: event
    event_type: shell_command.garage
action:
  - service: notify.pushbullet
    data:
      title: 'Jarvis'
      message: 'Garageport is activated.'
