alias: Aktiver "Privacy mode"
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.privacy_mode
    to: 'on'
action:
  - service: media_player.volume_set
    entity_id: media_player.ca01
    data:
      volume_level: 0
