alias: 'Lukk persienner ved høy temp'
initial_state: 'on'
trigger:
  - platform: numeric_state
    entity_id: sensor.netatmo_stue_temperature
    above: 25
action:
  - service: mqtt.publish
    data:
      topic: HA/cover
      payload: 'ned'
  - service: notify.alle
    data:
      title: 'Jarvis'
      message: 'Synes det er varmt og lukker nå persienner'
