alias: Dim av lys når TV viser noe
initial_state: 'on'
trigger:
  platform: state
  entity_id: media_player.atv_stua
  from: "paused"
  to: "playing"
action:
  - service: light.turn_on
    data:
      entity_id: light.h01
      brightness: 80