alias: 'Morgen radio, ukedager 07:00, hjemme'
initial_state: 'on'
trigger:
  platform: time
  after: '07:00:00'
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: device_tracker.iphone
    state: 'home'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.ca01
      media_content_id: http://tx-bauerno.sharp-stream.com/http_live.php?i=radionorge_no_mp3
      media_content_type: audio/mp4
