alias: 'Morgen radio, ukedager 07:00, hjemme'
initial_state: 'on'
trigger:
  platform: time
  after: '06:45:00'
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: device_tracker.iphone
    state: 'home'
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.radio
      option: "Radio Norge"
