alias: Velkommen hjem
initial_state: 'on'
trigger:
  - platform: state
    entity_id:
      - device_tracker.theos_iphone
      - device_tracker.pi_e6653
    to: 'home'
    for: '00:02:00'
action:
  - service: tts.google_say
    entity_id: media_player.ca01
    data_template:
      language: "no"
      message: >
        {% set person = trigger.to_state.attributes.friendly_name%}
        {%- macro greeting_sentence(person) -%}
        {{ [
        "Velkommen hjem! " ~ person,
        "Gjett hvem som er hjemme? "  ~ person +" er!",
        "Alle sammen: " ~ person + " er hjemme igjen.",
        "Velkommen hjem " ~ person + ".  Vi har savnet deg. eller i hvertfall Skybert gjorde.",
        "Godt 책 komme hjem n책, Sett deg ned, hvil hode og strekk p책 beina! Velkommen tilbake " ~ person,
        "Du kan bli her s책 lenge du vil, du er velkommen hjem " ~ person,
        "Heisann " ~ person + " Velkommen hjem!",
        person ~ "! Du er hjemme!"
        ] | random }}
        {%- endmacro -%}
        "{{greeting_sentence(person)}}"
