#######################################################################################################################################
##  Kjeller: Temeratur, lys og vaskerom
#######################################################################################################################################
homeassistant:
  customize:
    group.vaskerom:
      friendly_name: "Vaskerommet"
      hidden: false
    switch.w01:
      friendly_name: "Vaskemaskin"
      icon: mdi:washing-machine
    switch.w02:
      friendly_name: "Tørketrommel"
      icon: mdi:washing-machine
    switch.w03:
      friendly_name: "Kaffe"
      icon: mdi:coffee
    automation.rf01:
      hidden: true
    switch.rf01:
      hidden: true
    automation.rf06:
      hidden: true
    switch.rf06:
      hidden: true
    sensor.netatmo_kjellersoverom_min_temp:
      hidden: true
    sensor.netatmo_kjellersoverom_max_temp:
      hidden: true
    light.kjeller: #Tradfri gruppe Kjellerkrok
      hidden: true
    light.tradfri_bulb_e27_opal_1000lm:
      friendly_name: "Kjellerkrok"
    switch.basement_door_status:
      hidden: true   
    binary_sensor.basement_door:
      friendly_name: "Kjellerdør"

group:
  vaskerom:
    control: hidden
    entities:
      - binary_sensor.torketrommel
      - binary_sensor.vaskemaskin
      - binary_sensor.basement_door
  
input_boolean:
  rf01:
    name: Kjellerlys
    icon: mdi:lightbulb
  rf06:
    name: Kjellerstue
    icon: mdi:lightbulb
sensor:
  - platform: netatmo
    station: Kjeller
    modules:
      Kjellersoverom:
        - temperature
        - humidity
        - min_temp
        - max_temp
        - battery_vp
      Kjellerstue:
        - temperature
        - co2
        - pressure
        - noise
        - humidity
binary_sensor:
  - platform: template
    sensors:
      basement_door:
        value_template: "{{ is_state('switch.basement_door_status', 'on') }}"
        device_class: door

switch:
  - platform: wake_on_lan
    name: Flash
    mac_address: "2C-56-DC-DC-3E-E9"
    host: 192.168.1.25
  - platform: rfxtrx
    automatic_add: True
    devices:
      0b11000000c02e1a01010f70:
        name: rf01
  - platform: rfxtrx
    devices:
      0b110000013346760a000070:
        name: Basement door status
      0b11000d03f70bf20e010f70:
        name: rf06

#wemo:
#  static:
#   - 192.168.1.48
#   - 192.168.1.49
#   - 192.168.1.253
