#######################################################################################################################################
##  Persienner: Opp/Ned - Auto ned 25°C
#######################################################################################################################################
homeassistant:
  customize:
    group.persienner:
      friendly_name: "Persienner"
      hidden: false
    script.tilt_ned:
      hidden: true
    script.tilt_opp:
      hidden: true
    sensor.mqttcover:
      hidden: true

group:
  persienner:
    entities:
      - cover.persienner
      - cover.perienner_tilt
script:
  tilt_opp:
    sequence:
      - service: cover.open_cover
        entity_id: cover.persienner
      - delay: "00:00:01"
      - service: cover.stop_cover
        entity_id: cover.persienner
      - service: mqtt.publish
        data:
          topic: HA/cover
          payload: "-"
  tilt_ned:
    sequence:
      - service: cover.close_cover
        entity_id: cover.persienner
      - delay: "00:00:01"
      - service: cover.stop_cover
        entity_id: cover.persienner
      - service: mqtt.publish
        data:
          topic: HA/cover
          payload: "-"
cover:
  - platform: mqtt
    command_topic: "HA/cover"
    state_topic: "HA/cover/state"
    name: "Perienner tilt"
    qos: 0
    retain: true
    payload_open: "opp"
    payload_close: "ned"
  - platform: rfxtrx
    devices:
      071a000001020301:
        name: Persienner
sensor:
  - platform: mqtt
    name: mqttcover
    state_topic: "HA/cover"
automation:
  - alias: "Persienner tilt MQTT"
    trigger:
      platform: state
      entity_id: sensor.mqttcover
    action:
      service: script.turn_on
      data_template:
        entity_id: "script.tilt_{{trigger.to_state.state}}"
        
  - alias: "Lukk persienner ved høy temp"
    initial_state: "on"
    trigger:
      - platform: numeric_state
        entity_id: sensor.netatmo_stue_temperature
        above: 25
    action:
      - service: cover.close_cover
        entity_id: cover.persienner
      - service: notify.alle
        data:
          title: "HelleBOT"
          message: "Det er varmt inne, lukker nå persiennene"
