camera:
  - platform: mjpeg
    name: RV3 Rena
    mjpeg_url: http://webkamera.vegvesen.no/kamera?id=185544
    
  - platform: synology
    url: http://192.168.1.3:5000
    username: HAuser
    password: !secret synology-password
    verify_ssl: True
    
  - platform: netatmo
  
  #- platform: rpi_camera
  
- platform: generic
  still_image_url: http://192.168.1.163:5004/cam.jpg
  username: !secret rpiu
  password: !secret rpip
