#######################################################################################################################################
##  Configurator
#######################################################################################################################################
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218