binary_sensor:
  - platform: template
    sensors:
      torketrommel:
        value_template: >-
          {%- if states.switch.w02.attributes.current_power_w %}
              {{ states.switch.w02.attributes.current_power_w > 0.4}}
          {%  else %}
              0
          {%- endif %}
        friendly_name: 'Tørketrommel'

automation:
  alias: 'Alert when dryer is done'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.torketrommel
    from: "on"
    to: "off"
  action:
    - service: notify.alle
      data:
        title: 'HelleBOT'
        message: 'Tørketrommelen er ferdig.'
