binary_sensor:
  - platform: template
    sensors:
      torketrommel:
        value_template: >-
          {%- if states.switch.w02.attributes.current_power_w %}
              {{ states.switch.w02.attributes.current_power_w > 2}}
          {%  else %}
              0
          {%- endif %}
        friendly_name: "Tørketrommel"
