binary_sensor:
  - platform: template
    sensors:
      torketrommel:
        value_template: '{{ states.switch.w02.attributes.current_power_w > 0.4}}'
        friendly_name: 'Tørketrommel'

automation:
  alias: 'Alert when dryer is done'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.torketrommel
    from: "on"
    to: "off"
  action:
    - service: notify.pushbullet
      data:
        title: 'Jarvis'
        message: 'Tørketrommelen er ferdig.'
wemo:
  static:
    - 192.168.1.49
