cover:
  - platform: mqtt
    state_topic: "HA/garage/state"
    command_topic: "HA/garage"
    name: "Garasjeport"
    qos: 0
    retain: true
    payload_open: "opp"
    payload_close: "ned"
    state_open: "opp"
    state_closed: "ned"
    optimistic: false
    
sensor:
  - platform: mqtt
    name: "MQTT garage sensor"
    state_topic: "HA/garage"

automation:
  - alias: Garage Get state from sensor
    trigger:
      platform: state
      entity_id: sensor.garage_status
    action:
      service: mqtt.publish
      data_template:
        topic: "HA/garage/state"
        payload_template: '{{trigger.to_state.state}}'
        
  - alias: Garage move door
    trigger:
      platform: state
      entity_id: sensor.mqtt_garage_sensor
    action:
      service: script.turn_on
      entity_id: script.garage
