cover:
  - platform: mqtt
    # Denne aktiveres når magnet er ok state_topic: "HA/garage/state"
    state_topic: "HA/garage"
    command_topic: "HA/garage"
    name: "Garasjeport"
    qos: 0
    retain: true
    payload_open: "opp"
    payload_close: "ned"
    state_open: "opp"
    state_closed: "ned"
    optimistic: false
sensor:
  - platform: mqtt
    name: "MQTT garage sensor"
    state_topic: "HA/garage"
  - platform: template
    sensors:
      garage_status:
        value_template: '{%- if is_state("switch.garasjeport_status","on") %}opp{% elif is_state("switch.garasjeport_status","off") %}ned{%else%}error_reading_state{%- endif %}'
        icon_template: '{%- if is_state("switch.garasjeport_status", "on") %}mdi:garage-open{%else%}{%- elif is_state_attr("switch.garasjeport_status", "off") %}mdi:garage{%- endif %}'

automation:
  - alias: Garage Get state from sensor
    trigger:
      platform: state
      entity_id: sensor.garage_status
    action:
      service: mqtt.publish
      data_template:
        topic: "HA/garage/state"
        payload_template: '{{trigger.to_state.state}}'
  - alias: Garage move door
    trigger:
      platform: state
      entity_id: sensor.mqtt_garage_sensor
    action:
      service: script.turn_on
      entity_id: script.garage
