#######################################################################################################################################
##  Garasje: Garasjeport - opp/ned - auto opp 0700 - varsel
#######################################################################################################################################
homeassistant:
  customize:
    cover.garasjeport:
      device_class: garage
    group.garage:
      friendly_name: "Garasje"
      hidden: false
    script.garage:
      icon: mdi:garage
      hidden: true
    switch.garasjeport:
      hidden: false

group:
  garage:
    control: hidden
    entities:
      - cover.garasjeport
  view_garge:
    control: hidden
    view: yes
    icon: mdi:garage
    entities:
      - group.garage
      - camera.utekamera
      - automation.activate_garageport
      - group.netatmo_ute
cover:
  - platform: mqtt
    state_topic: "HA/garage"
    command_topic: "HA/garage"
    name: "Garasjeport"
    qos: 0
    retain: true
    payload_open: "opp"
    payload_close: "ned"
    state_open: "opp"
    state_closed: "ned"
    optimistic: false

switch:
  - platform: mqtt
    name: "Garasjeport"
    state_topic: "esp4/gpio/15"
    command_topic: "esp4/gpio/15"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true
               
script:
  garage:
    alias: Garasjeport
    sequence:
      - service: switch.turn_on
        entity_id: switch.garasjeport
      - delay: '00:00:01'
      - service: switch.turn_off
        entity_id: switch.garasjeport
      - service: notify.pushbullet
        data:
          title: "HelleBOT"
          message: "Jeg har ordnet garasjeporten for deg"
