############################################################################
## Google assistant
############################################################################
google_assistant:
  project_id: !secret gprojectid
  client_id: !secret gclientid
  access_token: !secret gaccesstoken
  agent_user_id: !secret gagentuser
  api_key: !secret gapikey
  exposed_domains:
    - switch
    - light
    - group
    - script
    - cover
    - input_boolean
    
homeassistant:
  customize_glob:
    "switch.rf*":
      google_assistant: false
############################################################################
