############################################################################
## Home Assistant info
############################################################################
sensor:
  - platform: command_line
    name: 'PyPi HA Version'
    command: curl -s https://github.com/home-assistant/home-assistant/releases/latest | awk -F'/' '{print $8}' | awk -F'"' '{print $1 }'
    
homeassistant:
  customize:
    sensor.pypi_ha_version:
      hidden: true
