############################################################################
## Homebridge
############################################################################
homeassistant:
  customize_domain:
    light:
      homebridge_visible: true
    switch:
      homebridge_visible: true
    cover:
      homebridge_visible: true
############################################################################
