############################################################################
## Home Assistant info
############################################################################
sensor:
  - platform: command_line
    name: 'PyPi HA Version'
    command: curl -s https://api.github.com/repos/home-assistant/home-assistant/releases/latest | grep tag_name | awk -F'"' '{print $4}'
    
homeassistant:
  customize:
    sensor.pypi_ha_version:
      hidden: true
