############################################################################
## Home Assistant info
############################################################################
sensor:
  - platform: rest
    name: 'PyPi HA Version'
    resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
    
homeassistant:
  customize:
    sensor.pypi_ha_version:
      hidden: true
