############################################################################
## Homebridge
############################################################################
homeassistant:
  customize_domain:
    light:
      homebridge_visible: true
    switch:
      homebridge_visible: true
    cover:
      homebridge_visible: true
    input_boolean:
      homebridge_visible: true
  customize_glob:
    "switch.rf*":
      homebridge_visible: false
############################################################################
