#######################################################################################################################################
##  Huset: Samling med nyttige spaker i huset
#######################################################################################################################################
homeassistant:
  customize:
    group.house:
      friendly_name: "Huset"
      hidden: false
    light.kjeller: #Tradfri gruppe Kjellerkrok
      hidden: true
    light.tradfri_bulb_e27_opal_1000lm:
      friendly_name: "Kjellerkrok"
    light.soverom_gutten: #Tradfri gruppe
      hidden: true
    light.tradfri_bulb_e27_w_opal_1000lm_2:
      friendly_name: "Soverom gutten"

group:
  house:  
    control: hidden
    entities:
      - light.h02
      - light.h03
      - switch.lyslenke
      - switch.lyslenke2
      - input_boolean.rf01
      - light.tradfri_bulb_e27_w_opal_1000lm_2
      - light.tradfri_bulb_e27_opal_1000lm
      - input_boolean.rf06
      - script.restart
      - input_boolean.privacy_mode
      
  view_home_light:
    control: hidden
    view: yes
    icon: mdi:home
    entities:
      - group.stue
      - group.house
      - group.garage
      - group.all_lights
      - group.netatmo_easy
      - input_select.radio
      - group.persienner
      - group.radio

