#######################################################################################################################################
##  Devices / iPad Pro
#######################################################################################################################################
homeassistant:
  customize:
    sensor.superlangbeins_2017_battery_level:
      hidden: true
    sensor.superlangbeins_ipro_battery_level:
      hidden: true
    sensor.superlangbeins_2017_battery_state:
      hidden: true
    sensor.superlangbeins_ipro_battery_state:
      hidden: true
    device_tracker.superlangbeins_ipro:
      hidden: true
    device_tracker.superlangbeins_2017:
      hidden: true
    sensor.phone_to_home_superlangbeins_ipro:
      hidden: true
    sensor.phone_to_home_superlangbeins_2017:
      hidden: true
#######################################################################################################################################
sensor:
  - platform: template
    sensors:
      template_superlangbeins_ipro:
        friendly_name: Superlangbeins iPro
        value_template: "{%if (states.device_tracker.superlangbeins_ipro.state) != 'not_home' %}{{states.device_tracker.superlangbeins_ipro.state}}{%- elif is_state('sensor.phone_to_home_superlangbeins_ipro', 'unknown')%}Error getting location{%- else -%}{{states.sensor.phone_to_home_superlangbeins_ipro.state}} Minutes to home{%- endif %}"
        icon_template: "{{states.sensor.superlangbeins_ipro_battery_level.attributes.icon}}"
      template_superlangbeins_2017:
        friendly_name: Superlangbeins 2017
        value_template: "{%if (states.device_tracker.superlangbeins_2017.state) != 'not_home' %}{{states.device_tracker.superlangbeins_2017.state}}{%- elif is_state('sensor.phone_to_home_superlangbeins_2017', 'unknown')%}Error getting location{%- else -%}{{states.sensor.phone_to_home_superlangbeins_2017.state}} Minutes to home{%- endif %}"
        icon_template: "{{states.sensor.superlangbeins_2017_battery_level.attributes.icon}}"  
#######################################################################################################################################
  - platform: google_travel_time
    name: Phone To Home Superlangbeins iPro
    api_key: !secret googleapi
    origin: device_tracker.superlangbeins_ipro
    destination: zone.home
  - platform: google_travel_time
    name: Phone To Home Superlangbeins 2017
    api_key: !secret googleapi
    origin: device_tracker.superlangbeins_2017
    destination: zone.home
#######################################################################################################################################
