#######################################################################################################################################
##  Barnerom2:
#######################################################################################################################################
homeassistant:
  customize:
    light.soverom_gutten: #Tradfri gruppe
      hidden: true
    light.tradfri_bulb_e27_w_opal_1000lm_2:
      friendly_name: "Barnerom2"
