#######################################################################################################################################
##  Barnerom:
#######################################################################################################################################
homeassistant:
  customize:
    light.h02:
      friendly_name: Barnerom
    light.gutta:
      hidden: true

#media_player:
 # - platform: cast
  #  host: 192.168.1.47