#######################################################################################################################################
##  Kjøkken:
#######################################################################################################################################
homeassistant:
  customize:
    automation.rf06:
      hidden: true
    switch.rf06:
      hidden: true

input_boolean:
  rf06:
    name: Kaffe
    icon: mdi:coffee
switch:
  - platform: rfxtrx
    automatic_add: True
    devices:
      0b11000d03f70bf20e010f70:
        name: rf06

automation:
  alias: Slå av kaffetrakter etter to timer
  initial_state: "on"
  trigger:
    - platform: state
      entity_id: input_boolean.rf06
      to: "on"
  action:
    - delay:
        minutes: 120
    - service: input_boolean.turn_off
      entity_id: input_boolean.rf06