switch:
  - platform: mqtt
    name: "Lyslenke"
    state_topic: "esp2/gpio/13"
    command_topic: "esp2/gpio/13"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true
homeassistant:
  customize:
    switch.lyslenke:
      icon: mdi:lightbulb
