switch:
  - platform: mqtt
    name: "Lyslenke2"
    state_topic: "esp3/gpio/13"
    command_topic: "esp3/gpio/13"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 0
    retain: true
homeassistant:
  customize:
    switch.lyslenke2:
      icon: mdi:lightbulb
