#######################################################################################################################################
##  Soverom: 
#######################################################################################################################################
homeassistant:
  customize:
    light.soverom:
      hidden: true
    light.h03:
      friendly_name: Soverom
