#######################################################################################################################################
##  Mobil lokasjon:
#######################################################################################################################################
homeassistant:
  customize:
    device_tracker.ec9bf3b218e4: #Samsung S6 FruSheriff
      icon: mdi:cellphone-android
      hidden: false
    device_tracker.ac5f3edd3981: #Samsung S7 Sheriff
      icon: mdi:cellphone-android
      hidden: false
    group.enheter:
      friendly_name: "Enheter"
      hidden: false
    sensor.superlangbeins_ipro_battery_level:
      hidden: true
    sensor.superlangbeins_ipro_battery_state:
      hidden: true
    sensor.superlangbein_battery_level:
      hidden: true
    sensor.superlangbein_battery_state:
      hidden: true
    sensor.yvind_sin_iphone_battery_level:
      hidden: true
    sensor.yvind_sin_iphone_battery_state:
      hidden: true

group:
  enheter:
    control: hidden
    entities:
      - device_tracker.ec9bf3b218e4
      - device_tracker.ac5f3edd3981
      - sensor.template_theos_iphone
      - sensor.template_noah_sin_ipad
      - sensor.template_superlangbeins_ipro
      - sensor.template_superlangbeins_2017

zone:
  - name: Jobb
    latitude: !secret z3la
    longitude: !secret z3lo
    radius: 80
    icon: mdi:account-multiple

  - name: Jobben
    latitude: !secret z4la
    longitude: !secret z4lo
    radius: 80
    icon: mdi:account-multiple
    
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
 # - platform: owntracks

 
