############################################################################
##  Motion sensor
############################################################################
binary_sensor:
  - platform: mqtt
    name: "PIR Hallway"
    state_topic: "/ESP5/PIR01"
    payload_on: 1
    payload_off: 0
    device_class: motion
