#######################################################################################################################################
##  Netatmo: 
#######################################################################################################################################
homeassistant:
  customize:
    group.netatmo:
      friendly_name: "Netatmo"
      hidden: false
    group.netatmo_easy:
      friendly_name: "Netatmo Easy"

netatmo:
  api_key: !secret netatmo-apikey
  secret_key: !secret netatmo-secretkey
  username: !secret mail
  password: !secret netatmo-password
group:
  netatmo:
    control: hidden
    entities:
      - sensor.netatmo_stue_temperature
      - sensor.netatmo_stue_co2
      - sensor.netatmo_stue_humidity
      - sensor.netatmo_stue_noise
      - sensor.netatmo_stue_pressure
      - sensor.netatmo_ute_temperature
      - sensor.netatmo_ute_max_temp
      - sensor.netatmo_ute_min_temp
      - sensor.netatmo_ute_humidity
      - sensor.netatmo_ute_battery
      - sensor.netatmo_kjellerstue_temperature
      - sensor.netatmo_kjellerstue_co2
      - sensor.netatmo_kjellerstue_humidity
      - sensor.netatmo_kjellerstue_noise
      - sensor.netatmo_kjellerstue_pressure
      - sensor.netatmo_kjellersoverom_temperature
      - sensor.netatmo_kjellersoverom_humidity
      - sensor.netatmo_kjellersoverom_battery
      - binary_sensor.home_someone_known
      - binary_sensor.home_motion
      - binary_sensor.home_someone_unknown
  netatmo_easy:
    control: hidden
    entities:
      - sensor.netatmo_stue_temperature
      - sensor.netatmo_kjellerstue_temperature
      - sensor.netatmo_kjellersoverom_temperature
      - sensor.netatmo_ute_temperature
      - sensor.netatmo_ute_max_temp
      - sensor.netatmo_ute_min_temp
      - sensor.netatmo_stue_co2
      - sensor.netatmo_kjellerstue_co2
      - sensor.netatmo_stue_humidity
      - sensor.netatmo_kjellerstue_humidity

