#######################################################################################################################################
##  Nettverk: ping, dns
#######################################################################################################################################
homeassistant:
  customize:
    switch.flash:
      friendly_name: "Flash"
      icon: mdi:windows
    device_tracker.c8f733eddd2f:
      icon: mdi:ubuntu
    device_tracker.hostspace:
      friendly_name: "WWW"
      icon: mdi:wifi
    group.network:
      friendly_name: "Nettverk"
      hidden: false
    sensor.speedtest_ping:
      friendly_name: Ping
      icon: mdi:signal-variant
    sensor.speedtest_download:
      friendly_name: Download
      icon: mdi:download
    sensor.speedtest_upload:
      friendly_name: Upload
      icon: mdi:upload
    sensor.pihole_ads_percentage_blocked_today:
      hidden: true
    sensor.pihole_dns_queries_today:
      hidden: true
    sensor.pihole_domains_blocked:
      hidden: true
    sensor.pihole_dns_unique_domains:
      hidden: true
    sensor.pihole_dns_queries_forwarded:
      hidden: true
    sensor.pihole_dns_queries_cached:
      hidden: true
group:
  network:
    control: hidden
    entities:
      - switch.flash
      - device_tracker.c8f733eddd2f
      - device_tracker.hostspace
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_dns_unique_clients
      - sensor.ha_uptime
      - binary_sensor.pir_hallway
      

device_tracker:
  - platform: ping
    hosts:
      hosthome: 192.168.1.25
      hostspace: 8.8.4.4
sensor:
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: pi_hole
    host: 192.168.1.165
  - platform: openhardwaremonitor
    host: 192.168.1.25
  - platform: uptime
    name: HA Uptime
switch:
  - platform: wake_on_lan
    name: Flash
    mac_address: "2C-56-DC-DC-3E-E9"
    host: 192.168.1.25
  - hadockermon:
    host: 192.168.1.205
