#######################################################################################################################################
##  Notifikasjoner: varsler av diverse slag
#######################################################################################################################################
homeassistant:
  customize:
    automation.varsling_lav_temp_ukedager_0703_hjemme:
      icon: mdi:snowflake
      hidden: false

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet-apikey
  - name: pushbullet2
    platform: pushbullet
    api_key: !secret pushbullet-apikey2
    
  - name: Alle
    platform: group
    services:
      - service: pushbullet
      - service: pushbullet2
