#######################################################################################################################################
##  Notifikasjoner: varsler av diverse slag
#######################################################################################################################################
homeassistant:
  customize:
    automation.varsling_lav_temp_ukedager_0703_hjemme:
      icon: mdi:snowflake
      hidden: false

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet-apikey
  - name: pushbullet2
    platform: pushbullet
    api_key: !secret pushbullet-apikey2
    
  - name: Alle
    platform: group
    services:
      - service: pushbullet
      - service: pushbullet2
    
    
automation:
  - alias: "Send påminnelse på angitt tid"
    trigger:
      platform: time
      after: "11:30:00"
    action:
      service: notify.alle
      data:
        message: "Tid for lunsj"
      
  - alias: "Velkommen hjem"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id:
          - device_tracker.theos_iphone
          - device_tracker.sheriffen
          - device_tracker.frusheriff
        to: "home"
        for: "00:02:00"
    action:
      - service: tts.google_say
        entity_id: media_player.ca01
        data_template:
          language: "no"
          message: >
            {% set person = trigger.to_state.attributes.friendly_name%}
            {%- macro greeting_sentence(person) -%}
            {{ [
            "Velkommen hjem! " ~ person,
            "Gjett hvem som er hjemme? "  ~ person +" er!",
            "Alle sammen: " ~ person + " er hjemme igjen.",
            "Velkommen hjem " ~ person + ".  Vi har savnet deg. eller i hvertfall Skybert gjorde.",
            "Godt å komme hjem nå, Sett deg ned, hvil hode og strekk på beina! Velkommen tilbake " ~ person,
            "Du kan bli her så lenge du vil, du er velkommen hjem " ~ person,
            "Heisann " ~ person + " Velkommen hjem!",
            person ~ "! Du er hjemme!"
            ] | random }}
            {%- endmacro -%}
            "{{greeting_sentence(person)}}"
            
  - alias: "Batteri Alarm for iPad"
    initial_state: "on"
    trigger:
      - platform: numeric_state
        entity_id: sensor.superlangbeins_ipro_battery_level
        below: 20
    action:
      - service: notify.alle
        data:
          title: "HelleBOT"
          message: "iPad Pro batteriet er lavt, koble til lader"
          
  - alias: "Varsling temp, ukedager 07:03, hjemme"
    initial_state: True
    hide_entity: false
    trigger:
      - platform: time
        after: "07:03:00"
    condition:
      - condition: state
        entity_id: input_boolean.workday_tomorrow
        state: "on"
    action:
      - service: notify.alle
        data_template:
          title: "HelleBOT"
          message: "{%- if  states.sensor.netatmo_ute_temperature.state| float < 3 -%}Det er kaldt! {{ states.sensor.netatmo_ute_temperature.state }} grader, lurt å holde seg inne i dag :){%- else -%}Gradestokken viser {{ states.sensor.netatmo_ute_temperature.state }} grader, ha en fin dag :){%- endif %}"
