#######################################################################################################################################
##  Radio
#######################################################################################################################################
homeassistant:
  customize:
    automation.morgen_radio:
      icon: mdi:radio
      hidden: false
    script.webradio_start:
      hidden: true
    script.webradio_stop:
      hidden: true

group:
  Radio:
    control: hidden
    entities:
      - input_select.radio
input_select:
  radio:
    name: Velg radiokanal
    options:
      - "Stopp"
      - "P4"
      - "NRK P3"
      - "Radio Norge"
      - "Solør Radio"
    initial: "Stopp"
    icon: mdi:radio
    
script:
  webradio_start:
    alias: Start webradio
    sequence:
      - service: media_player.play_media
        data_template:
          entity_id: media_player.ca01
          media_content_id: >
            {% if is_state("input_select.radio", "P4") %}
              http://stream.p4.no/p4_aac_lq
            {%-elif is_state("input_select.radio", "Radio Norge") %}
              http://tx-bauerno.sharp-stream.com/http_live.php?i=radionorge_no_mp3
            {%-elif is_state("input_select.radio", "Solør Radio") %}
              http://109.169.96.11:8000/solor.mp3
            {%-elif is_state("input_select.radio", "NRK P3") %}
              http://lyd.nrk.no/nrk_radio_p3_mp3_h
            {% else %}
            {% endif %}
          media_content_type: "audio/mp4"
  webradio_stop:
    alias: Stop webradio
    sequence:
      - service: media_player.media_stop
        entity_id: media_player.ca01

automation:
  - alias: "Web-radio in the livingroom"
    initial_state: "on"
    trigger:
      - platform: state
        entity_id: input_select.radio
    action:
      - service_template: script.turn_on
        data_template:
          entity_id: "{%if is_state('input_select.radio','Stopp')%}script.webradio_stop{%else%}script.webradio_start{%endif%}"  
        
  
  - alias: "Morgen radio"
    initial_state: "on"
    trigger:
      platform: time
      after: "06:45:00"
    condition:
      - condition: state
        entity_id: input_boolean.workday_tomorrow
        state: "on"
      - condition: state
        entity_id: device_tracker.sheriffen
        state: "home"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.radio
          option: "NRK P3"