#######################################################################################################################################
##  Theme fun
#######################################################################################################################################
homeassistant:
  customize:
    automation.theme:
      icon: mdi:skull
      hidden: true

group:
  Theme:
    control: hidden
    entities:
      - input_select.theme
input_select:
  theme:
    name: Velg tema
    options:
      - "DarkOrange"
      - "Lucky"
      - "Dark"
      - "Happy"
      - "Sad"
      - "Sunny"
      - "Neon"
      - "NightSky"
      - "Tokyo"
      - "Tokyo2"
      - "Pink"
      - "Default"
    initial: "Default"
    icon: mdi:palette
    
############################################################################
## Themes for the frontend
############################################################################
frontend:
  themes:
    darkorange:
      font-size: 4px
      primary-color: "#FFA500"
      primary-background-color: "#303030"
      secondary-background-color: "#303030"
      paper-card-background-color: "#424242"
      paper-item-icon-color: "#FFA500"
      primary-text-color: "#FFFFFF"
      secondary-text-color: "rgba(255, 255, 255, 0.7)"
      disabled-text-color: "rgba(255, 255, 255, 0.5)"
      divider-color: "rgba(255, 255, 255, 0.12)"
      paper-card-header-color: "#FFFFFF"
      paper-listbox-background-color: "#424242"
      paper-listbox-color: "#FFFFFF"
      paper-grey-200: "#616161"
      paper-toggle-button-checked-ink-color: "#FFA500"
      paper-toggle-button-checked-button-color: "#FFA500"
      paper-toggle-button-checked-bar-color: "#FFA500"
      paper-slider-knob-color: "#FFA500"
      paper-slider-knob-start-color: "#FFA500"
      paper-slider-pin-color: "#FFA500"
      paper-slider-active-color: "#FFA500"
      paper-slider-secondary-color: "#33F2D8"
    happy:
      primary-color: pink
    sad:
      primary-color: blue
    lucky:
      primary-color: orange
    sunny:
      primary-color: yellow
    dark:
      primary-color: black
    sky:
      primary-color: white
    nightsky:
      primary-color: purple
    neon:
      primary-color: "#00ff00"
    tokyo:
      primary-color: "#b400ff"
    tokyo2:
      primary-color: "#FF00B4"

#---------------------------------------------------------------------------
    pink:
      primary-color: pink
############################################################################
