#######################################################################################################################################
##  Universet: Vær, sol, måne og tid 
#######################################################################################################################################
homeassistant:
  customize:
    sun.sun:
      hidden: false
  
group:
  Universet:
    control: hidden
    entities:
#      - sensor.date__time
      - sensor.yr_symbol
      - sensor.moon
      - sun.sun
      - sensor.kp_index
sensor:
  
  - platform: moon
  
  - platform: yr
    monitored_conditions:
      - symbol
       
  #- platform: time_date
  #  display_options:
  #    - 'date_time'
  
  - platform: command_line
    name: KP Index
    unit_of_measurement: KP
    command: " curl -s http://www.aurora-service.org/aurora-forecast/ | grep ' <span style="color: #0000ff;"> Kp' |awk '{print $15}'|awk -F '.' '{print $1}'"

camera:
  - platform: generic
    name: 'Nordlys'
    still_image_url: http://kho.unis.no/Quicklooks/SvalTrackII/bossekop.jpg
