binary_sensor:
  - platform: template
    sensors:
      vaskemaskin:
        value_template: >-
          {%- if states.switch.w01.attributes.current_power_w %}
              {{ states.switch.w01.attributes.current_power_w > 3}}
          {%  else %}
              0
          {%- endif %}
        friendly_name: "Vaskemaskin"
