#######################################################################################################################################
##  Workday Tomorrow
#######################################################################################################################################
automation:
  - alias: "Aktiver 'Workday Tomorrow'"
    initial_state: "on"
    trigger:
      platform: time
      after: "20:00:00"
    condition:
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.workday_tomorrow
#--------------------------------------------------------------        
  - alias: "Deaktiver 'Workday Tomorrow'"
    initial_state: "on"
    trigger:
      - platform: time
        after: "20:00:00"
      - platform: state
        entity_id: input_boolean.vacation_mode
        to: "on"
    condition:
      - condition: time
        weekday:
          - fri
          - sat
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.workday_tomorrow
#######################################################################################################################################
input_boolean:
  workday_tomorrow:
    name: "Aktiver 'Workday Tomorrow'"
    icon: mdi:factory
